/* tslint:disable */
/* eslint-disable */
/**
 * Aiven Platform List
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CloudResponse,
    CloudResponseFromJSON,
    CloudResponseToJSON,
} from '../models';

/**
 * 
 */
export class CloudsApi extends runtime.BaseAPI {

    /**
     * List all Aiven\'s clouds
     */
    async getCloudPlatformsRaw(): Promise<runtime.ApiResponse<CloudResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/clouds`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => CloudResponseFromJSON(jsonValue));
    }

    /**
     * List all Aiven\'s clouds
     */
    async getCloudPlatforms(): Promise<CloudResponse> {
        const response = await this.getCloudPlatformsRaw();
        return await response.value();
    }

}
