# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run prettier check
        run: npm run prettier:check

      - name: Run eslint check
        run: npm run lint

      - name: Run the tests and generate coverage report
        run: npm test -- --coverage

      - name: Build the app
        run: npm run build

      - name: Start server in the background
        run: npm start &

      - name: Install Cypress and run tests
        run: npm run cypress

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
